# Copyright (c) {% now 'utc', '%Y' %} {{cookiecutter.project_org}}
# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.
# See https://docs.zephyrproject.org/latest/kconfig.html for all possible options.

# Shell & Logging
CONFIG_PRINTK=y
CONFIG_SHELL=y
CONFIG_LOG=y
CONFIG_KERNEL_SHELL=y
CONFIG_DEVICE_SHELL=y

{% if cookiecutter.create_own_driver %}
#CONFIG_SENSOR=y
#CONFIG_BLINK=y{% else %}
#CONFIG_GPIO=y{% endif %}

# TODO
